services:
  dbtest:
    image: postgres
    container_name: dbtest
    restart: always
    ports: 
      - 1234:5432
    env_file:
      - .env.test
  
  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - dbtest
    env_file:
      - .env.test
